FROM node:20-alpine AS base

RUN npm i -g pnpm

FROM base AS dependencies

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base AS build

WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/web/node_modules ./web/node_modules
RUN pnpm --filter web build
RUN pnpm prune --prod

FROM base AS deploy

WORKDIR /app
COPY --from=build /app/web/dist/ ./web/dist/
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/web/node_modules ./web/node_modules
EXPOSE 3000

CMD [ "node", "web/dist/main.js" ]
